web:
  dockerfile: Dockerfile
  build: .
  ports:
   - "8080:8080"
   - "8088:8088"
  volumes:
   - .:/app
   - ./web/build.gradle.docker:/app/web/build.gradle
  volumes_from:
   - gradle
  stdin_open: true
  command: ./gradlew :web:run :backend:run
  
gradle:
  image: centos
  volumes:
   - ~/.gradle:/root/.gradle:rw